export default [
  {
    id: 1,
    firstName: "Emmy",
    lastName: "Expo",
    title: "Business Analyst",
    experience: 13,
    workedWith: [2, 3],
  },
  {
    id: 2,
    firstName: "Roman",
    lastName: "React",
    title: "Marketing Specialist",
    experience: 7,
    workedWith: [1, 3],
  },
  {
    id: 3,
    firstName: "Amir",
    lastName: "Angular",
    title: "Project Manager",
    experience: 3,
    workedWith: [1, 2],
  },
  {
    id: 4,
    firstName: "Matt",
    lastName: "Mongoose",
    title: "UX Designer",
    experience: 1,
    workedWith: [6],
  },
  {
    id: 5,
    firstName: "Zoey",
    lastName: "Zoom",
    title: "Sales Director",
    experience: 9,
    workedWith: [],
  },
  {
    id: 6,
    firstName: "Judy",
    lastName: "Jest",
    title: "Marketing Specialist",
    experience: 5,
    workedWith: [4],
  },
];
